name: sikuris_app
description: App para grupo de sikuris
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.40

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
